[package]
name = "audio_processing_static"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fundsp = "0.15.0"
hound = "3.5.0"
rustfft = "6.1.0"
